services:
  # In Docker
  # - DB_URL=postgres://app:app@db/
  # Outside Docker
  # - DB_URL=postgres://app:app@localhost:7377/
  db:
    image: couchdb
    restart: always
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    volumes:
      - db:/opt/couchdb/data
    ports:
      - '7377:5984'

volumes:
  db: