services:
  db:
    image: db
    build: ./db
    restart: always
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    volumes:
      - db:/opt/couchdb/data
    ports:
      - '7377:5984'

volumes:
  db: