services:
  # In Docker
  # - DATABASE_URL=postgres://app:app@db/
  # Outside Docker
  # - DATABASE_URL=postgres://app:app@localhost:7377/
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '7377:5432'

volumes:
  db: